In [1]:
import numpy as np

In [2]:
# Tính toán EigenDecomposition trên ma trận vuông A
# A = P.L.P_1
# P là ma trận các vector riêng
# L là ma trận các giá trị riêng
# P_1 là ma trận nghịch đảo của P

### Dẫn nhập vector riêng, giá trị riêng

In [3]:
# v là vector riêng và lambda là giá trị riêng của ma trận A, nếu như: A.v = lambda.v
# ví dụ:
A = np.array([[2,3],[0,1]]) # ma trận A
A

array([[2, 3],
       [0, 1]])

In [4]:
v = np.array([1,0]) # vector v
v

array([1, 0])

In [5]:
ld = 2 # biến lambda
A.dot(v)

array([2, 0])

In [6]:
ld*v

array([2, 0])

In [7]:
# kết luận: 
# Ta có: A.v = lambda.v
# ld=2 là giá trị riêng và v = (1,0) là vector riêng của ma trận A

# Tính toán EigenDecomposition trên ma trận vuông A

In [8]:
A = np.array([[1,3,5],[2,4,6],[7,8,9]])
A

array([[1, 3, 5],
       [2, 4, 6],
       [7, 8, 9]])

In [9]:
# dùng thư viện
from numpy.linalg import eig

In [10]:
values, vectors = eig(A)

In [11]:
values

array([ 1.64339811e+01, -2.43398113e+00, -3.67161364e-16])

In [12]:
vectors # mỗi cột là một vector

array([[ 0.35321681,  0.5923436 ,  0.40824829],
       [ 0.45205763,  0.44327356, -0.81649658],
       [ 0.81907374, -0.67278348,  0.40824829]])

### Chỉ xét một giá trị riêng và một vector riêng (đầu tiên)

In [13]:
# xét một giá trị riêng thứ nhất
values[0]

16.433981132056612

In [14]:
# xét một vector riêng thứ nhất
vectors[:,0]

array([0.35321681, 0.45205763, 0.81907374])

In [15]:
# so sánh A.v = lambda.v
A.dot(vectors[:,0]) # A.v

array([ 5.80475838,  7.42910655, 13.46064233])

In [16]:
values[0]*vectors[:,0] # lambda.v

array([ 5.80475838,  7.42910655, 13.46064233])

### Xét tất cả giá trị riêng và vector riêng

In [17]:
# dùng thư viện để tạo ma trận đường chéo là các giá trị riêng sắp giảm
from numpy import diag

In [18]:
L = diag(values) # tạo ma trận đường chéo là các giá trị riêng sắp giảm
L

array([[ 1.64339811e+01,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -2.43398113e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -3.67161364e-16]])

In [19]:
A.dot(vectors) # A.v

array([[ 5.80475838e+00, -1.44175315e+00, -7.77156117e-16],
       [ 7.42910655e+00, -1.07891947e+00, -1.11022302e-15],
       [ 1.34606423e+01,  1.63754230e+00, -7.77156117e-16]])

In [20]:
values*vectors # lambda.v

array([[ 5.80475838e+00, -1.44175315e+00, -1.49892999e-16],
       [ 7.42910655e+00, -1.07891947e+00,  2.99785998e-16],
       [ 1.34606423e+01,  1.63754230e+00, -1.49892999e-16]])

# Tạo lại ma trận A = P.L.P_1
- P là ma trận các vector riêng
- L là ma trận các giá trị riêng
- P_1 là ma trận nghịch đảo của P

In [21]:
from numpy.linalg import inv

In [27]:
values

array([ 1.64339811e+01, -2.43398113e+00, -3.67161364e-16])

In [22]:
P = vectors
P_1 = inv(P)
L = diag(values)

In [23]:
P

array([[ 0.35321681,  0.5923436 ,  0.40824829],
       [ 0.45205763,  0.44327356, -0.81649658],
       [ 0.81907374, -0.67278348,  0.40824829]])

In [24]:
P_1

array([[ 0.405701  ,  0.56884304,  0.73198508],
       [ 0.93982544,  0.2094647 , -0.52089604],
       [ 0.73484692, -0.79608417,  0.12247449]])

In [25]:
L

array([[ 1.64339811e+01,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -2.43398113e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -3.67161364e-16]])

In [26]:
P.dot(L).dot(P_1) # chính là ma trận A

array([[1., 3., 5.],
       [2., 4., 6.],
       [7., 8., 9.]])