## Bài 1

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [2,3,1],
              [6,3,4],
              [5,2,7]])
A = np.random.randint(1,30, (3000, 30))

In [3]:
k = 2

In [4]:
from numpy.linalg import eig

### Tính PCA bằng tay

In [5]:
A_mean = np.mean(A, axis=0, keepdims=True)
A_mean

array([[14.742     , 15.18633333, 15.08266667, 14.704     , 15.035     ,
        15.00066667, 15.03966667, 14.74466667, 14.90266667, 15.018     ,
        15.284     , 15.20566667, 14.92466667, 14.85566667, 15.065     ,
        15.155     , 15.14366667, 15.26966667, 14.962     , 14.85666667,
        15.09333333, 15.09733333, 14.73033333, 15.23366667, 15.10833333,
        15.15166667, 15.12866667, 15.00933333, 15.421     , 14.949     ]])

In [6]:
C = A - A_mean
C # dời trục

array([[ -5.742     ,  13.81366667,  -5.08266667, ...,  -3.00933333,
         -2.421     ,   2.051     ],
       [ 10.258     ,   7.81366667,   5.91733333, ..., -13.00933333,
        -14.421     , -10.949     ],
       [ -3.742     , -11.18633333,   6.91733333, ...,   9.99066667,
         -5.421     ,  -0.949     ],
       ...,
       [ -5.742     , -14.18633333,  13.91733333, ...,  -7.00933333,
         -2.421     , -12.949     ],
       [  4.258     ,  -0.18633333,   7.91733333, ...,   4.99066667,
         -0.421     ,  12.051     ],
       [-11.742     , -13.18633333,  -1.08266667, ...,   9.99066667,
         -7.421     ,  11.051     ]])

In [7]:
V = np.cov(C.T)
V

array([[ 6.90104395e+01,  5.80933645e-02,  4.31109837e+00,
        -1.00068023e-01, -4.76128710e-01, -3.02928976e-01,
         2.35645882e-01, -1.96608203e-01, -1.77270290e+00,
        -2.39448750e+00, -9.25036345e-01,  2.59659420e+00,
         1.29432878e+00, -2.02324575e+00, -3.04331444e-01,
         3.26741247e+00, -3.22041347e-01, -9.20732911e-01,
         6.68752251e-01, -1.01365122e+00, -1.89788596e+00,
         2.52095232e+00, -2.29733978e+00, -1.93778593e-01,
        -2.80798600e+00, -1.89216739e+00,  6.97428476e-01,
        -2.59286429e-03,  6.27493831e-01, -1.75007469e+00],
       [ 5.80933645e-02,  7.01536644e+01,  1.82253729e+00,
         1.92379593e+00,  1.54666055e+00,  1.44635790e+00,
        -7.54163610e-02, -2.00489719e-01,  3.79929754e-01,
        -4.15159053e-01,  7.31057019e-02,  2.20474569e+00,
        -4.93127265e-01,  7.05129154e-01,  4.75713571e-01,
         1.04513338e+00,  2.97088707e+00,  6.23960098e-01,
         1.25516572e+00, -1.97661776e+00, -7.82985440e-

In [8]:
values, vectors = eig(V)

In [9]:
values

array([56.62773691, 83.31354981, 81.77495417, 81.29967059, 80.1334155 ,
       80.36662357, 59.05873843, 77.92021281, 60.33456171, 61.09066693,
       61.74636258, 76.48155438, 76.04475126, 74.94922103, 74.58118565,
       73.14717629, 72.62816213, 71.65499385, 71.17687099, 70.93402643,
       63.25953479, 63.84578821, 64.42022183, 64.70431029, 69.10946003,
       65.78921704, 66.48843541, 66.87620656, 67.39359521, 68.5243729 ])

In [10]:
vectors

array([[-4.92433155e-01,  3.04329227e-01, -1.62617757e-01,
         1.81655468e-01, -1.58626587e-01,  3.32120524e-02,
         8.92681969e-02,  2.26507291e-01,  3.55227830e-02,
         5.91174576e-02,  1.82388436e-01,  1.06599338e-01,
         2.72026271e-01,  2.10990121e-01, -2.41590928e-02,
        -6.49853121e-02,  2.35330056e-01, -5.91301904e-02,
        -8.00607321e-02, -1.33117404e-01,  1.94652981e-01,
        -8.38189658e-02,  1.21662630e-01,  1.72666326e-01,
        -3.29992157e-01, -9.75557766e-02,  1.82433575e-01,
         1.50234030e-01, -2.00242036e-02,  2.39658434e-04],
       [ 4.77284403e-03,  5.39222916e-02,  1.64502117e-01,
         9.79432259e-02, -2.71503851e-01, -2.74722750e-01,
         2.32812316e-01,  1.17917362e-01, -3.68231112e-02,
        -8.85946731e-02, -1.26246765e-01,  6.11586866e-02,
         2.01472895e-02, -6.53113856e-02, -1.71466010e-01,
        -1.10929373e-01, -4.69063480e-01, -1.54193609e-02,
         9.39743622e-02,  1.11062288e-02,  1.34371639e-

In [11]:
V_T = vectors[:,:k]
V_T

array([[-0.49243315,  0.30432923],
       [ 0.00477284,  0.05392229],
       [ 0.25108989,  0.20362588],
       [-0.17810162, -0.01295745],
       [-0.02163852, -0.4437994 ],
       [ 0.02380617,  0.05563267],
       [ 0.01076065,  0.06623384],
       [-0.12250666, -0.0671409 ],
       [-0.24407859, -0.07087044],
       [-0.31713737, -0.09506442],
       [-0.13461206,  0.21828412],
       [ 0.16742704,  0.19920834],
       [ 0.06062676,  0.32827765],
       [-0.08492372, -0.02586669],
       [ 0.07019038, -0.00312481],
       [-0.00112839,  0.22311966],
       [-0.18158283,  0.09801997],
       [-0.04463864,  0.17257302],
       [ 0.09265445, -0.00974877],
       [-0.23780007, -0.03199699],
       [-0.2805317 , -0.13546074],
       [ 0.19794049, -0.10040538],
       [-0.11464089, -0.12452329],
       [-0.06364678, -0.1118867 ],
       [-0.06215499, -0.41739611],
       [-0.22472822, -0.11392072],
       [ 0.18853441, -0.20118754],
       [ 0.06904098, -0.09932221],
       [ 0.02071176,

In [12]:
P = V_T.T@C.T
P

array([[  8.29674328,  -3.39957382,   0.65321236, ...,   2.9502198 ,
        -12.06765802,   2.41045337],
       [  1.36324298,   4.63430151,  -6.18035941, ...,   2.65741143,
         -2.96768471,   4.59457086]])

In [13]:
A.T.shape

(30, 3000)

In [14]:
P.shape

(2, 3000)

### Tính bằng thư viện

In [15]:
from sklearn.decomposition import PCA

In [16]:
pca = PCA()

In [17]:
pca.n_components=k

In [18]:
pca.fit(A)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [19]:
pca.transform(A)

array([[ -4.80243268,  -7.16105281],
       [  2.99295915,  16.19216993],
       [ -4.44503581, -16.17043322],
       ...,
       [  7.66332135,   0.88646163],
       [ -9.04868169,  17.16436066],
       [ 13.26366396,   1.72330297]])

## Bài 2

In [20]:
P.T

array([[  8.29674328,   1.36324298],
       [ -3.39957382,   4.63430151],
       [  0.65321236,  -6.18035941],
       ...,
       [  2.9502198 ,   2.65741143],
       [-12.06765802,  -2.96768471],
       [  2.41045337,   4.59457086]])

In [21]:
pca.transform(A)

array([[ -4.80243268,  -7.16105281],
       [  2.99295915,  16.19216993],
       [ -4.44503581, -16.17043322],
       ...,
       [  7.66332135,   0.88646163],
       [ -9.04868169,  17.16436066],
       [ 13.26366396,   1.72330297]])

In [22]:
print(pca.components_.T)

[[ 1.36286363e-01  5.45154109e-02]
 [-1.77939350e-01 -1.13953507e-01]
 [-3.76356413e-02  1.73587601e-01]
 [-1.00062172e-01  1.86004291e-02]
 [-5.06192084e-01  9.44783007e-02]
 [-2.13354812e-02  3.40266289e-02]
 [ 2.06015903e-01 -2.12198397e-01]
 [ 3.45952500e-02 -1.46516544e-01]
 [ 1.32296237e-02 -5.07506634e-02]
 [-1.02692071e-01  1.59457123e-02]
 [ 2.59992791e-01 -9.45163392e-03]
 [-7.47702015e-02 -6.78355419e-02]
 [ 2.68533652e-02  3.63370458e-01]
 [-2.63029031e-01  3.05228087e-01]
 [ 4.73678469e-02 -4.79344775e-01]
 [ 2.15808576e-01 -2.15358097e-02]
 [-8.58681372e-02  1.76529941e-02]
 [ 1.90265764e-01  3.25899477e-02]
 [-3.91667252e-02 -2.12139521e-01]
 [ 1.78671906e-01  6.86484140e-02]
 [-9.63626355e-02 -3.88514628e-02]
 [-1.25768183e-01 -3.31049849e-01]
 [-1.39404861e-01 -1.42636820e-01]
 [-4.80679285e-04 -7.37314273e-02]
 [-4.30454210e-01 -1.47744537e-01]
 [-1.95221221e-01 -3.02565538e-01]
 [-2.33385859e-01  1.21818068e-01]
 [-4.40531605e-02 -2.88964957e-01]
 [ 1.83389247e-01 -1

In [23]:
V_T

array([[-0.49243315,  0.30432923],
       [ 0.00477284,  0.05392229],
       [ 0.25108989,  0.20362588],
       [-0.17810162, -0.01295745],
       [-0.02163852, -0.4437994 ],
       [ 0.02380617,  0.05563267],
       [ 0.01076065,  0.06623384],
       [-0.12250666, -0.0671409 ],
       [-0.24407859, -0.07087044],
       [-0.31713737, -0.09506442],
       [-0.13461206,  0.21828412],
       [ 0.16742704,  0.19920834],
       [ 0.06062676,  0.32827765],
       [-0.08492372, -0.02586669],
       [ 0.07019038, -0.00312481],
       [-0.00112839,  0.22311966],
       [-0.18158283,  0.09801997],
       [-0.04463864,  0.17257302],
       [ 0.09265445, -0.00974877],
       [-0.23780007, -0.03199699],
       [-0.2805317 , -0.13546074],
       [ 0.19794049, -0.10040538],
       [-0.11464089, -0.12452329],
       [-0.06364678, -0.1118867 ],
       [-0.06215499, -0.41739611],
       [-0.22472822, -0.11392072],
       [ 0.18853441, -0.20118754],
       [ 0.06904098, -0.09932221],
       [ 0.02071176,

In [24]:
pca.explained_variance_

array([81.59775507, 80.72719225])

In [25]:
tmp_val = values.copy()

In [26]:
def get_index(arr, v):
    for each in range(len(arr)):
        if arr[each] == v: return each
    return -1

In [29]:
import numpy as np
def get_reserve(values, vectors):
    val_sort = np.sort(values)[::-1]
    val_sort
    lst = [each for each in range(len(values))]
    result_order = []
    result = []
    for i in range(len(val_sort)):
        if val_sort[i] != values[i]:
            fake_index = get_index(values, val_sort[i])
            print(fake_index)
            index = lst[fake_index]
            result_order.append(index)
            lst.pop(fake_index)
            np.delete(values, fake_index)
        else:
            result_order.append(i)
    return val_sort, vectors[:,result_order], result_order

In [30]:
get_reserve(values, vectors)[2]

1
2
3
5
7
11
12
13
14
15
16
17
18


IndexError: list index out of range

In [ ]:
vectors