## Ví dụ 2: PCA tính bằng thư viện

In [17]:
import numpy as np
from sklearn.decomposition import PCA

In [18]:
np.random.seed(1)
A = np.random.randint(1,256,(3000,300))
A.shape

(3000, 300)

In [19]:
# create the transform
pca = PCA(n_components=3) # số cột là 3
# fit transform
pca.fit(A)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [20]:
# transform data (project data)
B = pca.transform(A) # với B là ma trận kết quả của phép chiếu
B

array([[-119.2025454 ,  -42.28661877,  -59.30859621],
       [  18.41577543,   37.25581671,   17.12419653],
       [  38.30814793,   56.23958315,  -28.23373286],
       ...,
       [  30.21648143,    3.09984366,  -90.80864801],
       [-102.85454643,   76.2939626 ,   20.14906368],
       [  73.90155673,   46.5527136 ,  -82.00141237]])

In [21]:
# in eigen vectors
print(pca.components_.T)

[[ 7.59939890e-02  1.30392546e-01 -3.17898017e-03]
 [ 2.85751984e-02 -3.05539571e-02 -1.78001592e-02]
 [-2.89975768e-02  1.08644826e-02  4.14926146e-02]
 [ 1.06541919e-03 -2.11599472e-02 -4.35930446e-03]
 [-3.95316472e-02  5.17970343e-02 -5.09556736e-02]
 [ 2.94726463e-02  3.95189141e-02  3.01764876e-02]
 [-9.85681382e-02 -4.49272641e-02  3.23054293e-02]
 [ 4.09293153e-02  7.60482451e-02 -6.27305237e-02]
 [-1.84985968e-03 -6.90737664e-02  2.32612737e-02]
 [ 1.01363373e-01 -3.23690819e-02  7.98580430e-02]
 [-2.45008616e-02  1.48760703e-03 -9.61906818e-03]
 [ 5.32320954e-02  4.96805973e-02 -3.57269299e-02]
 [ 5.64078122e-02  5.31696149e-02 -2.21096536e-02]
 [ 1.32227675e-01 -8.58737266e-02  2.31721517e-02]
 [-1.06425943e-01  6.56102395e-02 -7.60932122e-02]
 [ 7.40298437e-02  7.29868001e-02  4.04554788e-02]
 [ 3.63329164e-02 -5.11830035e-02 -1.71414909e-02]
 [-8.76408013e-02 -5.49427506e-02  8.20982017e-03]
 [ 3.96389879e-02  1.17263281e-02 -9.55305757e-03]
 [-5.64750404e-02  1.17981425e-

In [22]:
# in eigen values
print(pca.explained_variance_) # các giá trị đơn giảm dần

[8959.55703743 8798.38219265 8660.43142223]


In [23]:
# xem tỷ lệ nén
pca.explained_variance_ratio_

array([0.00551161, 0.00541246, 0.0053276 ])

In [24]:
sum(pca.explained_variance_ratio_)

0.016251666775548505