In [1]:
import numpy as np
from numpy import array
from numpy import diag
from numpy import dot
from scipy.linalg import svd
from numpy import zeros
from scipy.linalg import inv

# Phân rã Singular Value Decomposition (SVD)
### A = U.S.V_T
- A ma trận mxn
- U ma trận trực giao mxm (U_T = U_1)
- S ma trận đường chéo mxn, các giá trị riêng
- V_T là ma trận nghịch đảo của ma trận trực giao V nxn

# A là ma trận vuông

In [2]:
# A là ma trận vuông
A = array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# phân rã SVD
U, s, V_T = svd(A)

In [4]:
U

array([[-0.21483724,  0.88723069,  0.40824829],
       [-0.52058739,  0.24964395, -0.81649658],
       [-0.82633754, -0.38794278,  0.40824829]])

In [5]:
s

array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16])

In [6]:
V_T

array([[-0.47967118, -0.57236779, -0.66506441],
       [-0.77669099, -0.07568647,  0.62531805],
       [-0.40824829,  0.81649658, -0.40824829]])

In [29]:
# tạo ma trận đường chéo
S = diag(s)
S

array([[1.68481034e+01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.06836951e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 4.41842475e-16]])

In [30]:
# tạo lại ma trận A = U.S.V_T
U.dot(S.dot(V_T))

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

# A không là ma trận vuông

In [31]:
# A không là ma trận vuông
A = array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
# phân rã SVD
U, s, V_T = svd(A)

In [33]:
U

array([[-0.2298477 ,  0.88346102,  0.40824829],
       [-0.52474482,  0.24078249, -0.81649658],
       [-0.81964194, -0.40189603,  0.40824829]])

In [34]:
V_T

array([[-0.61962948, -0.78489445],
       [-0.78489445,  0.61962948]])

In [35]:
s

array([9.52551809, 0.51430058])

In [36]:
# tạo ma trận đường chéo
S = zeros(A.shape)
S

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
diag(s)

array([[9.52551809, 0.        ],
       [0.        , 0.51430058]])

In [38]:
S[:A.shape[1],:A.shape[1]] = diag(s)
S

array([[9.52551809, 0.        ],
       [0.        , 0.51430058],
       [0.        , 0.        ]])

In [39]:
# tạo lại ma trận A = U.S.V_T
U.dot(S.dot(V_T))

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [40]:
V = V_T

In [41]:
# V là ma trận trực giao
V.dot(V_T)

array([[1.00000000e+00, 9.02083186e-18],
       [9.02083186e-18, 1.00000000e+00]])

In [42]:
# U là ma trận trực giao
U.dot(U.T)

array([[ 1.00000000e+00, -6.06602824e-17, -8.06921612e-17],
       [-6.06602824e-17,  1.00000000e+00,  2.08316059e-17],
       [-8.06921612e-17,  2.08316059e-17,  1.00000000e+00]])