In [6]:
import numpy as np
from numpy import array
from numpy import diag
from numpy import dot
from scipy.linalg import svd
from numpy import zeros
from scipy.linalg import inv

# Sử dụng SVD để giảm chiều dữ liệu
- Số thuộc tính (cột) lớn hơn số quan sát (dòng) rất nhiều
- Tạo ra một ma trận có chiều thấp hơn so với chiều của ma trận gốc

In [7]:
A = np.arange(1,31)
A = np.reshape(A,(3,10))
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [8]:
U, s, V_T = svd(A)

In [9]:
U

array([[-0.19101157,  0.89266338,  0.40824829],
       [-0.51371859,  0.26348917, -0.81649658],
       [-0.8364256 , -0.36568503,  0.40824829]])

In [10]:
S = zeros(A.shape)
S[:A.shape[0],:A.shape[0]] = diag(s)
S

array([[9.69657342e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 7.25578339e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.43064394e-15, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00]])

In [11]:
V_T # V_T.T = V

array([[-0.24139304, -0.25728686, -0.27318068, -0.2890745 , -0.30496832,
        -0.32086214, -0.33675595, -0.35264977, -0.36854359, -0.38443741],
       [-0.53589546, -0.42695236, -0.31800926, -0.20906617, -0.10012307,
         0.00882003,  0.11776313,  0.22670623,  0.33564933,  0.44459242],
       [-0.71590327,  0.22125777,  0.35844894,  0.23137425,  0.12099174,
         0.27768425, -0.35015608,  0.05691924, -0.00338669, -0.19723014],
       [-0.03274747, -0.17891449, -0.37608172,  0.89207072, -0.08211107,
        -0.11995167,  0.02920549, -0.06831525, -0.05443306, -0.00872147],
       [-0.07588946, -0.05763181, -0.30552732, -0.08865234,  0.92223855,
        -0.12098055, -0.00525156, -0.09919877, -0.09845351, -0.07065325],
       [ 0.06629874,  0.08438747, -0.47449715, -0.0967393 , -0.08248279,
         0.8362855 ,  0.03555043, -0.13520148, -0.138849  , -0.09475243],
       [-0.33592049,  0.16549299,  0.06013546, -0.02444478, -0.06055817,
        -0.0839398 ,  0.85527901, -0.15616659

In [12]:
k = 2 # chọn ra 2 cột
S = S[:,:k] # thu hẹp k cột
S

array([[96.96573419,  0.        ],
       [ 0.        ,  7.25578339],
       [ 0.        ,  0.        ]])

In [13]:
V_T = V_T[:k,:] # thu hẹp k dòng
V_T

array([[-0.24139304, -0.25728686, -0.27318068, -0.2890745 , -0.30496832,
        -0.32086214, -0.33675595, -0.35264977, -0.36854359, -0.38443741],
       [-0.53589546, -0.42695236, -0.31800926, -0.20906617, -0.10012307,
         0.00882003,  0.11776313,  0.22670623,  0.33564933,  0.44459242]])

In [153]:
# tạo lại ma trận A = U.S.V_T
U.dot(S.dot(V_T))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.]])

In [154]:
# so sánh U.S = A.V do V là ma trận trực giao
U.dot(S)

array([[-18.52157747,   6.47697214],
       [-49.81310011,   1.91182038],
       [-81.10462276,  -2.65333138]])

In [155]:
A.dot(V_T.T)

array([[-18.52157747,   6.47697214],
       [-49.81310011,   1.91182038],
       [-81.10462276,  -2.65333138]])