In [4]:
import numpy as np
from sklearn.decomposition import TruncatedSVD
from scipy.linalg import inv

In [3]:
# sử dụng thư viện để giảm chiều dữ liệu
# define array
A = np.arange(1,31)
A = np.reshape(A,(3,10))
print('A=')
print(A)
# svd
svd = TruncatedSVD(n_components=2)
svd.fit(A)
print('\nT=')
T = svd.transform(A)
print(T)

A=
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

T=
[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]


In [3]:
from sklearn import datasets

In [11]:
digits = datasets.load_digits()
X = digits.data
X.shape # 1797 dòng và 64 cột

(1797, 64)

In [12]:
svd = TruncatedSVD(n_components=10)
svd.fit(X)
print('\nresult=')
result = svd.transform(X)
print(result)


result=
[[ 45.86127719  -1.1921159   21.10005922 ...   0.39676545   1.30997815
   -1.39000658]
 [ 55.52967927   7.86176976 -20.48719881 ...   1.53818943  -4.73674322
    3.41005503]
 [ 55.8278837    6.91459585  -9.66245268 ...   2.29645165 -16.8433059
   -1.12374233]
 ...
 [ 65.52698526  10.65872859  -6.29456061 ...  -2.30209756  -4.47331665
   -1.72414295]
 [ 58.60616587  -4.91125238  12.723152   ...   0.50970698  -1.63373454
    6.44117825]
 [ 64.44823101  -0.45551341   7.04184366 ...  -8.30355896   3.37801283
   -1.41471833]]


In [13]:
print(result.shape)

(1797, 10)
